### ISSUE TITLE
Newest version blocking whole "s3.amazonaws.com" domain

### ISSUE THREAD

**Issue by pguizeline** [davidonzo/Threat-Intel#12]
Hi!

Thanks for your list and all your work!

Your newest available list seems to be blocking "s3.amazonaws.com" as a whole, and personally I can't see it as a bad domain. Maybe a typo?

Thanks!

**Comment by davidonzo** [comment]
Hi,

Thanks for your advise.
It's somithing similar to issues #7 #8 #9 and #10 

In this case the related malicious url is: hXXps://s3.amazonaws.com/agilecrm/panel/uploaded-logo/talibtalib/1604421730900/efdf344f4fdsdff[.]exe

As for any other similar case, I whitelisted the domain, maintaining the related url in the URLs list.

A new job was lauched to update the domainlist. I think it will be disposal in 10 minutes.
Please, check it and close the issue if you think the problem was solved.

Thank you very much, and feel free to open other issue for similar matter.
--
Davide

**Comment by pguizeline** [comment]
Thank you very much for the fast reply and fix!
