### ISSUE TITLE
files.slack.com blocked which caused all Slack's files including images blocked

### ISSUE THREAD

**Issue by PeterDaveHello** [davidonzo/Threat-Intel#16]
Sorry I'm not familiar with this project, but looks like it's a trusted source of some block lists ;)

Just found that files.slack.com was added in 4a4b3f31f5cd91adac19338bcdcaedf277c7af8f two days ago(2021-01-29)

```json
{
  "created": "2021-01-29T18:18:25.000Z",
  "created_by_ref": "identity--5e9dad84-c570-47a4-bcc8-0315c0a80112",
  "id": "indicator--5fe903b9-ea3e-4ce0-b4a0-4d41717e8846",
  "kill_chain_phases": [
    {
      "kill_chain_name": "misp-category",
      "phase_name": "Network activity"
    }
  ],
  "labels": [
    "misp:type=\"url\"",
    "misp:category=\"Network activity\"",
    "misp:to_ids=\"True\""
  ],
  "modified": "2021-01-29T18:18:25.000Z",
  "pattern": "[url:value = 'https://files.slack.com/files-pri/T01KVP6T295-F01LJK0P7UL/download/previewdocument-29-1.exe?pub_secret=bc95c3fed1']",
  "type": "indicator",
  "valid_from": "2021-01-29T18:18:25Z",
  "valid_until": "2021-01-29T18:18:25Z"
}
```
(from `stix2/87d3fe09-b054-4ee9-bc34-106e8f849578.json`)

The affect may be huge, all the blockers applied the lists from here will block the images from Slack, the cause could be abuse by only certain users, maybe need to be whitelisted in this case? 

Very appreciate for your help :D

**Comment by davidonzo** [comment]
Fixed. See the conversation on twitter: Fixed, see the conversation on twitter: https://twitter.com/AdamSurak/status/1356152687289655297

**Comment by PeterDaveHello** [comment]
Thanks @davidonzo, I'll close this issue now!

BTW, would you have any suggestion if we'd like to know more details behind this update? Really appreciate your work on this project :D

**Comment by davidonzo** [comment]
A malicious file has been detected from the files.slack.com server. The file url is hXXps://files.slack.com/files-pri/T01KVP6T295-F01LJK0P7UL/download/previewdocument-29-1.exe?pub_secret=bc95c3fed1
The issue was firstly reported by urlhaus.abuse.ch.

Last 2021-01-29 my lab ingested the URL IoC from abuse.ch, than the url was detonated and the malware has been downloaded and analyzed using automation tools.
The IoC sharing method in this case add the affected domain to the domainlist, the relate url in the URLs list and create a analyze summary in various format.

Considering the almost automation procedure, I implemented a whitelist, to avoid the inclusion of certains domains in the domains list (usually file sharing services).

That is. Easy but usually effective.

**Comment by PeterDaveHello** [comment]
Really appreciate the details you shared, also the effort on this project :D
